### PR TITLE
Added automatic generation of SECRET_KEY setting

### PR DESCRIPTION
**Pull request by ihabunek**
The first time settings are loaded, the secret key is automatically
generated and saved to settings/secret.py, which is added to .gitignore.
This way the secret key is kept out of base settings which are commited
into the repository.

Uses generation algorithm used by django startproject command.

### CODE REVIEW

**Comment by ihabunek** [comment]
Bump.

**Comment by senko** [comment]
Damn, I missed the update from 11 days ago, sorry! Not sure how I managed to miss it.

Looks mostly okay, one question tho: should `gen_key_secret()` be a separate function? I'd just copy these two lines to `ensure_secret_key_file()` (one less extra symbol defined in settings).

**Comment by ihabunek** [comment]
Separate function seemed more modular, no other reason. Removed the 'chars' variable as well. That's more or less optimal now.

**Comment by ihabunek** [comment]
Facepalm, chars would not be defined as a symbol since it's in a function. Oh, well, no matter.

**Comment by senko** [comment]
Looks great, thx. Merging. (BTW yeah, GitHub didn't notify me the pull request was updated, it just fires notifications for comments apparently).

**Pull request merged**
